name:                inveterate
version:             0.1.0.0
github:              "turnage/inveterate"
license:             AGPL
author:              "Payton Turnage"
maintainer:          "maintenance@paytonturnage.com"
copyright:           "2020 Payton Turnage"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A file-change watcher.
category:            Productivity

description:         Please see the README on GitHub at <https://github.com/turnage/inveterate#readme>

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - NamedFieldPuns

dependencies:
- base >= 4.7 && < 5
- bytestring
- process
- system-fileio
- system-filepath
- options
- text
- stm
- hinotify
- regex-tdfa
- utf8-string
- stringsearch
- hashtables

library:
  source-dirs: src

executables:
  inveterate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inveterate
